import { defineType, defineField } from 'sanity'

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'organization', title: 'Organization Info', default: true },
    { name: 'contact', title: 'Contact Information' },
    { name: 'social', title: 'Social Media' },
    { name: 'impactStats', title: 'Impact Statistics' },
    { name: 'branding', title: 'Branding' },
  ],
  fields: [
    // Organization Info Group
    defineField({
      name: 'orgName',
      title: 'Organization Name',
      type: 'string',
      group: 'organization',
      description: 'The official name of your organization. Appears in headers, footers, and meta tags.',
      initialValue: 'The Ladder',
      validation: (Rule) => Rule.required().error('Organization name is required'),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'organization',
      description: 'A short, memorable phrase that captures your mission. Example: "Helping people climb over life\'s barriers, one rung at a time"',
      initialValue: 'Helping people climb over life\'s barriers, one rung at a time',
      validation: (Rule) => Rule.max(100).warning('Keep taglines under 100 characters for best display'),
    }),
    defineField({
      name: 'mission',
      title: 'Mission Statement',
      type: 'text',
      rows: 4,
      group: 'organization',
      description: 'Your full mission statement. This appears on the About page and may be used in grant applications. Be clear and compelling.',
      validation: (Rule) => Rule.max(500).warning('Mission statements work best under 500 characters'),
    }),
    defineField({
      name: 'foundedYear',
      title: 'Year Founded',
      type: 'number',
      group: 'organization',
      description: 'The year your organization was established. Displayed in trust badges (e.g., "Serving Birmingham Since 2021").',
      initialValue: 2021,
      validation: (Rule) => Rule.min(2000).max(2030).error('Please enter a valid year'),
    }),
    defineField({
      name: 'ein',
      title: 'EIN (Tax ID)',
      type: 'string',
      group: 'organization',
      description: 'Your 501(c)(3) Employer Identification Number. Format: XX-XXXXXXX. Displayed on donation pages for tax purposes.',
      initialValue: '82-0737087',
      validation: (Rule) => Rule.regex(/^\d{2}-\d{7}$/).error('EIN must be in format XX-XXXXXXX (e.g., 82-0737087)'),
    }),

    // Contact Information Group
    defineField({
      name: 'phone',
      title: 'Primary Phone Number',
      type: 'string',
      group: 'contact',
      description: 'Main contact phone number. Format: (XXX) XXX-XXXX. This appears in the header, footer, and throughout the site.',
      initialValue: '(205) 522-1162',
      validation: (Rule) => Rule.required().error('A contact phone number is required'),
    }),
    defineField({
      name: 'email',
      title: 'Primary Email Address',
      type: 'string',
      group: 'contact',
      description: 'Main contact email. This is where general inquiries will be directed. Example: info@the-ladder.org',
      initialValue: 'info@the-ladder.org',
      validation: (Rule) => Rule.required().email().error('Please enter a valid email address'),
    }),
    defineField({
      name: 'address',
      title: 'Physical Address',
      type: 'object',
      group: 'contact',
      description: 'Your organization\'s physical location. Used in the footer and for local SEO.',
      options: { collapsible: true, collapsed: false },
      fields: [
        { 
          name: 'street', 
          type: 'string', 
          title: 'Street Address',
          description: 'Include suite/unit number if applicable',
        },
        { 
          name: 'city', 
          type: 'string', 
          title: 'City', 
          initialValue: 'Birmingham',
          validation: (Rule) => Rule.required(),
        },
        { 
          name: 'state', 
          type: 'string', 
          title: 'State', 
          initialValue: 'AL',
          description: 'Use 2-letter abbreviation (e.g., AL)',
          validation: (Rule) => Rule.required().length(2),
        },
        { 
          name: 'zip', 
          type: 'string', 
          title: 'ZIP Code',
          description: '5-digit ZIP code',
          validation: (Rule) => Rule.regex(/^\d{5}(-\d{4})?$/).error('Enter a valid ZIP code'),
        },
      ],
    }),

    // Social Media Group
    defineField({
      name: 'socialLinks',
      title: 'Social Media Links',
      type: 'object',
      group: 'social',
      description: 'Links to your social media profiles. These appear in the footer and may be used for sharing.',
      options: { collapsible: true, collapsed: false },
      fields: [
        { 
          name: 'facebook', 
          type: 'url', 
          title: 'Facebook Page URL',
          description: 'Full URL to your Facebook page. Example: https://facebook.com/theladder',
        },
        { 
          name: 'instagram', 
          type: 'url', 
          title: 'Instagram Profile URL',
          description: 'Full URL to your Instagram profile. Example: https://instagram.com/theladder_bham',
        },
        { 
          name: 'linkedin', 
          type: 'url', 
          title: 'LinkedIn Page URL',
          description: 'Full URL to your LinkedIn company page',
        },
        { 
          name: 'twitter', 
          type: 'url', 
          title: 'Twitter/X Profile URL',
          description: 'Full URL to your Twitter/X profile',
        },
      ],
    }),

    // Impact Statistics Group
    defineField({
      name: 'impactStats',
      title: 'Impact Statistics',
      type: 'object',
      group: 'impactStats',
      description: 'Key metrics that demonstrate your impact. These numbers appear prominently across the site (homepage, success stories, about page). Update these as your organization grows!',
      options: { collapsible: true, collapsed: false },
      fields: [
        { 
          name: 'individualsHelped', 
          type: 'string', 
          title: 'Individuals Helped',
          description: 'Total number of people helped. Include "+" for approximations. Example: "500+"',
          initialValue: '500+',
          validation: (Rule) => Rule.required(),
        },
        { 
          name: 'individualsHelpedLabel', 
          type: 'string', 
          title: 'Individuals Helped Label',
          description: 'Text shown below the number. Example: "Individuals Helped" or "Lives Changed"',
          initialValue: 'Individuals Helped',
        },
        { 
          name: 'successRate', 
          type: 'string', 
          title: 'Success Rate',
          description: 'Percentage of barriers successfully removed. Include "%". Example: "95%"',
          initialValue: '95%',
          validation: (Rule) => Rule.required(),
        },
        { 
          name: 'successRateLabel', 
          type: 'string', 
          title: 'Success Rate Label',
          description: 'Text shown below the percentage. Example: "Success Rate"',
          initialValue: 'Success Rate',
        },
        { 
          name: 'responseTime', 
          type: 'string', 
          title: 'Response Time',
          description: 'Average time to first response. Example: "24hr" or "24 Hours"',
          initialValue: '24hr',
          validation: (Rule) => Rule.required(),
        },
        { 
          name: 'responseTimeLabel', 
          type: 'string', 
          title: 'Response Time Label',
          description: 'Text shown below the time. Example: "Response Time"',
          initialValue: 'Response Time',
        },
        { 
          name: 'directImpact', 
          type: 'string', 
          title: 'Direct Impact Percentage',
          description: 'Percentage of donations going to direct services. Example: "100%"',
          initialValue: '100%',
        },
        { 
          name: 'directImpactLabel', 
          type: 'string', 
          title: 'Direct Impact Label',
          description: 'Text shown below the percentage. Example: "Direct Impact" or "To Direct Services"',
          initialValue: 'Direct Impact',
        },
        { 
          name: 'avgInvestment', 
          type: 'string', 
          title: 'Average Investment',
          description: 'Typical cost to remove a barrier. Include "$". Example: "$350"',
          initialValue: '$350',
        },
        { 
          name: 'avgInvestmentLabel', 
          type: 'string', 
          title: 'Average Investment Label',
          description: 'Text shown below the amount. Example: "Avg. Investment"',
          initialValue: 'Avg. Investment',
        },
        { 
          name: 'daysToResolution', 
          type: 'string', 
          title: 'Days to Resolution',
          description: 'Typical time to fully resolve a barrier. Example: "30" or "30 Days"',
          initialValue: '30',
        },
        { 
          name: 'daysToResolutionLabel', 
          type: 'string', 
          title: 'Days to Resolution Label',
          description: 'Text shown below the number. Example: "Days to Resolution"',
          initialValue: 'Days to Resolution',
        },
        { 
          name: 'longTermSuccess', 
          type: 'string', 
          title: 'Long-term Success Rate',
          description: 'Percentage of clients maintaining success long-term. Example: "85%"',
          initialValue: '85%',
        },
        { 
          name: 'longTermSuccessLabel', 
          type: 'string', 
          title: 'Long-term Success Label',
          description: 'Text shown below the percentage. Example: "Long-term Success"',
          initialValue: 'Long-term Success',
        },
      ],
    }),

    // Branding Group
    defineField({
      name: 'logo',
      title: 'Primary Logo',
      type: 'image',
      group: 'branding',
      description: 'Your main logo. Recommended: PNG or SVG with transparent background, at least 400px wide. Used in header and footer.',
      options: { hotspot: true },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alt Text',
          description: 'Describe the logo for accessibility. Example: "The Ladder logo"',
        },
      ],
    }),
    defineField({
      name: 'logoLight',
      title: 'Light Logo (for dark backgrounds)',
      type: 'image',
      group: 'branding',
      description: 'A light/white version of your logo for use on dark backgrounds. Optional but recommended.',
      options: { hotspot: true },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alt Text',
        },
      ],
    }),
    defineField({
      name: 'favicon',
      title: 'Favicon',
      type: 'image',
      group: 'branding',
      description: 'Small icon shown in browser tabs. Recommended: Square image, at least 32x32px.',
      options: { hotspot: true },
    }),
  ],
  preview: {
    prepare() {
      return { 
        title: 'Site Settings',
        subtitle: 'Organization info, contact, social media, and impact stats',
      }
    },
  },
})
